### PR TITLE
fix require module name

### PR DESCRIPTION
**Pull request by Ashing**
old require will cause issue by using 'pkg' pack app

### CODE REVIEW

**Comment by jtyjty99999** [comment]
> old require will cause issue by using 'pkg' pack app

why？

**Comment by Ashing** [comment]
> > old require will cause issue by using 'pkg' pack app
> 
> why？

I checked the code,here comes the reason:
egg-security package.json declare naoid(^1.1.1),install version will be 1.2.4 and it doesn't has 'non-secure' path.

**Comment by atian25** [comment]
I had try `nanoid@1.2.4` / `nanoid@1.3.4`, it does have `non-secure`

had you try to reinstall deps with no-lock-file ?

**Comment by atian25** [comment]
> egg-security package.json declare naoid(^1.1.1),install version will be 1.2.4 and it doesn't has 'non-secure' path.

- btw, it's `nanoid` not `naoid`
- and egg-security use `^1.1.1` which `^` will install the lastest version of v1, now will be 1.3.4

**Comment by Ashing** [comment]
> > egg-security package.json declare naoid(^1.1.1),install version will be 1.2.4 and it doesn't has 'non-secure' path.
> 
> * btw, it's `nanoid` not `naoid`
> * and egg-security use `^1.1.1` which `^` will install the lastest version of v1, now will be 1.3.4

My fault.
This issue only cause when pack app to one excutable with pkg.
It Seems like pkg can't solve module require of this kind.
I add code below to nanoid/index.js,also can fix the issue.
let nanoid = {
  'non-secure': require('./non-secure.js')
}
module.exports = nanoid

So what can i do now?

**Comment by atian25** [comment]
@jtyjty99999 use `non-secure` for performance purpose

maybe:

- find another package instead of nanoid with the same performance
- PR to `nanoid` to exports `non-secure` at index.js
- or issue to `pkg` to fixture how to support require path

**Comment by jtyjty99999** [comment]
> @jtyjty99999 use `non-secure` for performance purpose
> 
> maybe:
> 
> * find another package instead of nanoid with the same performance
> * PR to `nanoid` to exports `non-secure` at index.js
> * or issue to `pkg` to fixture how to support require path

I agree, may be we should contact to nanoid's maintainer

**Comment by atian25** [comment]
contact with PR :)

**Comment by Maledong** [comment]
@atian25：In fact this non-secure isn't the main problem, for the speed is 10 times slower, so I suggest the user using non-secure package. And this is good. 

For more please see https://github.com/eggjs/egg-security/pull/43

**Comment by ghost** [comment]
@Ashing：Thanks for your contribution!

First, nano's 'non-secure' really exists and you can directly refer that path, so this isn't the problem.
Then, as your web pack problem, I'm not sure whether the egg project will have the same senario or not?
I'll close this issue for so long a time, and you can re-open it if possible :)

**Pull request closed without merging**
