### PR TITLE
feat: csrf cookie support cookieOptions

### PR DESCRIPTION
**Pull request by damujiangr**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

 --

##### Description of change
add `config.security.csrf.cookieOptions`, custom cookie options for csrf token

### CODE REVIEW

**Comment by damujiangr** [comment]
@fengmk2 @atian25 please review, thank you

**Comment by atian25** [comment]
1. need unit test 
2. why and when should we need to custom cookie options?

**Comment by atian25** [comment]
ci is failed, need to reinstall node_modules to trigger egg-ci update github.yml to npminstall@5

**Comment by damujiangr** [comment]
> 1. need unit test
> 2. why and when should we need to custom cookie options?

```typescript
// before  
config.security = {
  csrf: {
    cookieName: 'abc',
  }
};

// after, support more cookie options
config.security = {
  csrf: {
    cookieName: 'abc',
    cookieOption: {
      httpOnly: true,
      secure: true,
    },
  }
};
```

**Review by hyj1991 — APPROVED** [review]
+1

**Comment by damujiangr** [comment]
> +1

my big bro, when to publish new package

**Comment by atian25** [comment]
2.11.0

**Comment by fengmk2** [comment]
@damujiangr Thanks!

**Pull request merged**
