### PR TITLE
fix: disable nosniff on redirect status

### PR DESCRIPTION
**Pull request by fengmk2**
from 300 ~ 308
see https://github.com/jshttp/statuses/blob/master/index.js#L30

### CODE REVIEW

**Comment by dead-horse** [comment]
nosniff 导致 redirect 失败的链接有么？

**Comment by fengmk2** [comment]
@dead-horse 嗯，拦截了 redirect 的跳转

**Comment by fengmk2** [comment]
https://tracert.alipay.com/iframe.js

**Review by popomore — APPROVED** [review]

**Comment by fengmk2** [comment]
2.2.3

**Comment by XadillaX** [comment]
@fengmk2 是否要 backport 到 1.x？

**Comment by fengmk2** [comment]
@XadillaX https://github.com/eggjs/egg-security/pull/39

**Pull request merged**
